services:
  users-api:
    build: ./
    command: ./wait-for-postgres.sh db ./users-api
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=users-api-db

  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=users-api-db
    ports:
      - "5432:5432"
